version: "3"
services:
  focalors:
    container_name: focalors
    build:
      context: ./docker/focalors
      args:
        REPO_URL: "https://github.com/stkevintan/focalors.git"
        REPO_BRANCH: "master"
    environment:
      TZ: Asia/Shanghai
      FOCALORS_YUNZAI_HOST: miao-yunzai
      REDIS_URI: redis://miao-redis:6379
    volumes:
      - ./focalors/logs/wechat-bridge:/app/focalors/packages/wechat-bridge/logs
      - ./focalors/logs/yunzai-client:/app/focalors/packages/yunzai-client/logs
      - ./focalors/entrypoint.sh:/entrypoint.sh
    restart: always
    depends_on:
      miao-yunzai: { condition: service_healthy }

  miao-yunzai:
    container_name: miao-yunzai
    build:
      context: ./docker/yunzai
      args:
        REPO_URL: "https://gitee.com/TimeRainStarSky/Yunzai.git"
        REPO_BRANCH: "main"
    restart: always
    volumes:
      - ./yunzai/config/:/app/Miao-Yunzai/config/config/ # Bot基础配置文件
      - ./yunzai/logs:/app/Miao-Yunzai/logs # 日志文件
      - ./yunzai/data:/app/Miao-Yunzai/data # 数据文件
      - ./yunzai/entrypoint.sh:/entrypoint.sh # 自定义启动脚本
      - ./yunzai/plugins:/app/Miao-Yunzai/plugins #plugin 目录
    depends_on:
      miao-redis: { condition: service_healthy }
    deploy:
      resources:
        limits:
          memory: 2G
    healthcheck:
      test: curl --fail http://localhost:2536 || exit 1
      start_period: 20s
      interval: 60s
      retries: 5
      timeout: 10s

  miao-redis:
    container_name: miao-redis
    image: redis:alpine
    restart: always
    volumes:
      # 前往 https://download.redis.io/redis-stable/redis.conf 下载配置文件，放入 ./redis/config 文件夹中
      # - ./redis/config:/etc/redis/    # Redis配置文件
      - ./redis/data:/data
      - ./redis/logs:/logs
    # command: /etc/redis/redis.conf    # 取消注释以应用Redis配置文件
    healthcheck:
      test: [ "CMD", "redis-cli", "PING" ]
      start_period: 10s
      interval: 5s
      timeout: 1s