/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface SocketOptions {
  recvTimeout?: number
  sendTimeout?: number
}
export function sum(a: number, b: number): number
export class Socket {
  options: SocketOptions
  constructor(options?: SocketOptions | undefined | null)
  connect(url: string): void
  send(req: Buffer): Buffer
  close(): void
  connected(): boolean
}
